
version: 2

models:
  - name: dim_customers
    description: "Customer data from the source system"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: name
        description: "name of the customer"
        data_tests:
          - not_null
      - name: location_id
        description: "foreign key to location table"
        data_tests:
          - not_null                    
      - name: address
        description: "address of the customer"
        data_tests:
          - not_null  
      - name: phone_number
        description: "phone number of the customer"
        data_tests:
          - not_null  

  - name: dim_locations
    description: "location data from the source system"
    columns:
      - name: location_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: country_name
        description: "name of the country"
        data_tests:
          - not_null

  - name: dim_products
    description: "product data from the source system"
    columns:
      - name: product_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: product
        description: "name of the product"
        data_tests:
          - not_null

  - name: fact_orders
    description: "orders data from the source system"
    columns:
      - name: order_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "foreign key to customer table"
        data_tests:
          - not_null
      - name: quantity
        description: "quantity of the order"
        data_tests:
          - not_null
      - name: price
        description: "price of the order"
        data_tests:
          - not_null
      - name: order_date
        description: "date of the order"
        data_tests:
          - not_null
      - name: customer_location_id
        description: "foreign key to location table"
        data_tests:
          - not_null
      - name: customer_name
        description: "name of the customer"
        data_tests:
          - not_null
      - name: customer_address
        description: "address of the customer"
        data_tests:
          - not_null
      - name: customer_phone_number
        description: "phone number of the customer"
        data_tests:
          - not_null
      - name: customer_country_name
        description: "name of the country"
        data_tests:
          - not_null

